{
 "title": "Kafka Inkless",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "0.50, 0.75, 0.95, 0.98, 0.99, 0.999"
   }
  ]
 },
 "panels": [
  { "title": "Throughput/Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestspersec{}[$__rate_interval])",
     "legendFormat": "{{request}} v{{version}}"
    }
   ]
  },
  {
   "title": "Bytes In/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesinpersec{topic!=\"\"}[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestspersec{request=\"Produce\"}[$__rate_interval])",
     "legendFormat": "{{request}} v{{version}}"
    }
   ]
  },
  {
   "title": "Fetch Consumer Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestspersec{request=\"FetchConsumer\"}[$__rate_interval])",
     "legendFormat": "{{request}} v{{version}}"
    }
   ]
  },
  {
   "title": "Bytes Out/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesoutpersec{topic!=\"\"}[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consume Path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_consume_inklessfetchmetrics_fetchtotaltime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Fetch File time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_consume_inklessfetchmetrics_fetchfiletime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Find Batches Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_consume_inklessfetchmetrics_findbatchestime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Plan Fetch time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_consume_inklessfetchmetrics_fetchplantime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Fetch Completion time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_consume_inklessfetchmetrics_fetchcompletiontime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Produce Path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_produce_filecommitter_filetotallifetime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "File size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_inkless_produce_filecommitter_filesize{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Upload and Commit time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_produce_filecommitter_fileuploadandcommittime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Upload time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_produce_filecommitter_fileuploadtime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Commit time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_inkless_produce_filecommitter_filecommittime{quantile=\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}