{
 "title": "Kafka Clients",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "benchmark_quantile",
    "label": "Benchmark Quantile",
    "query": {
     "query": "label_values(benchmark_consumer_e2e_latency,quantile)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Record send rate per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_topic_metrics_record_send_rate",
     "legendFormat": "{{host}}->{{topic}}"
    }
   ]
  },
  {
   "title": "Records per request (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_records_per_request_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network IO rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_network_io_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request size (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_size_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Batch Split rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_split_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_outgoing_byte_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Incoming byte rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_incoming_byte_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "IO wait time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_wait_time_ns_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Batch size (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg",
     "legendFormat": "avg@{{host}}"
    }
   ]
  },
  {
   "title": "Batch size (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_max",
     "legendFormat": "max@{{host}}"
    }
   ]
  },
  {
   "title": "Metadata wait time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_metadata_wait_time_ns",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_node_metrics_request_latency_avg",
     "legendFormat": "{{host}} {{client_id}} {{node_id}}"
    }
   ]
  },
  {
   "title": "Request Latency (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_node_metrics_request_latency_max",
     "legendFormat": "{{host}} {{client_id}} {{node_id}}"
    }
   ]
  },
  {
   "title": "Compression rate (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_compression_rate_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Record Queue time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_queue_time_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Record Queue time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_queue_time_max",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Record Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_error_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "IO time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_time_ns_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bufferpool wail time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_bufferpool_wait_time_ns",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Metadata age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_metadata_age",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Produce Throttle time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Record retry rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_retry_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Record sent rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_send_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Connection creation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_connection_creation_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_connection_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Fetch latency avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Commit Latency avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Records batch size (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_size_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_request_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_response_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Fetch throttle time avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bytes consumed per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{topic!=\"\"}",
     "legendFormat": "{{host}} <- {{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_outgoing_byte_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests in fligh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_requests_in_flight",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Incoming byte rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_incoming_byte_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Fetch size avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{topic!=\"\"}",
     "legendFormat": "{{host}} <- {{topic}}"
    }
   ]
  },
  {
   "title": "Select rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_select_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Sync rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_sync_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network IO rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_network_io_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Join rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_join_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Committed time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_committed_time_ns",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heartbeat rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_heartbeat_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "IO time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_io_time_ns_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "IO wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_io_wait_time_ns_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Time between poll (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_time_between_poll_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Commit sync time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_commit_sync_time_ns",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Last poll seconds ago",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_last_poll_seconds_ago",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Rebalance latency avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 138 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_latency_avg",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_connection_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Connection creation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_connection_creation_rate",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Failed rebalance rate per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 146 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_failed_rebalance_rate_per_hour",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Assigned Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_assigned_partitions",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}