{
 "title": "Postgres",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total number of transactions commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{datname=\"inkless\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"inkless\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Total amount of rows processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(pg_stat_statements_rows_total{datname=\"inkless\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time spent executing statements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_stat_statements_seconds_total{datname=\"inkless\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time spent writing blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_stat_statements_block_write_seconds_total{datname=\"inkless\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time spent reading blocks ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_stat_statements_block_read_seconds_total{datname=\"inkless\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}