services:
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/inkless?sslmode=disable"
      DATA_SOURCE_USER: "admin"
      DATA_SOURCE_PASS: "admin"
    command:
      - "--collector.stat_statements"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./../../../extra/prometheus/config/:/etc/prometheus/:Z

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./../../../extra/grafana/:/etc/grafana/provisioning/:Z