services:
  broker:
    image: aivenoy/kafka:4.1.0-inkless-SNAPSHOT
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "7070:7070" # prometheus metrics
      - "9999:9999" # jmx port
    environment:
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      # Inkless
      KAFKA_LOG_INKLESS_ENABLE: "true"

      ## Control Plane
      ### Postgresql
      KAFKA_INKLESS_CONTROL_PLANE_CLASS: "io.aiven.inkless.control_plane.postgres.PostgresControlPlane"
      KAFKA_INKLESS_CONTROL_PLANE_CONNECTION_STRING: "jdbc:postgresql://postgres:5432/inkless"
      KAFKA_INKLESS_CONTROL_PLANE_USERNAME: "admin"
      KAFKA_INKLESS_CONTROL_PLANE_PASSWORD: "admin"

      ## In-memory control plane
      # KAFKA_INKLESS_CONTROL_PLANE_CLASS: "io.aiven.inkless.control_plane.InMemoryControlPlane"

      ### In-memory storage
      KAFKA_INKLESS_STORAGE_BACKEND_CLASS: "io.aiven.inkless.storage_backend.in_memory.InMemoryStorage"

      # JMX
      KAFKA_JMX_PORT: 9999
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
      EXTRA_ARGS: -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=7070:/opt/prometheus-jmx-exporter/kafka.yml
    volumes:
      - ./../../../extra/prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --list"]
      interval: 5s
      timeout: 20s
      retries: 20
    depends_on:
      postgres:
        condition: service_healthy

  # Postgresql for control plane
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "inkless"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=inkless -U admin"]
      interval: 5s
      timeout: 20s
      retries: 20

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./../../../extra/prometheus/config/:/etc/prometheus/
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./../../../extra/grafana/:/etc/grafana/provisioning/

  # Demo
  create_topic:
    image: aivenoy/kafka:4.1.0-inkless-SNAPSHOT
    restart: "no"
    depends_on:
      broker:
        condition: service_healthy
    command: ["/opt/kafka/bin/kafka-topics.sh",
              "--bootstrap-server", "broker:19092",
              "--create",
              "--config", "inkless.enable=true",
              "--topic", "test-topic",
              "--partitions", "10"]

  producer:
    image: apache/kafka:4.0.0
    scale: 2
    depends_on:
      create_topic:
        condition: service_started
    command: ["/opt/kafka/bin/kafka-producer-perf-test.sh",
              "--producer-props", "bootstrap.servers=broker:19092", "batch.size=1000000", "linger.ms=500",
              "--topic", "test-topic",
              "--record-size", "1000",
              "--num-records", "10000000000",
              "--throughput", "-1"]

  consumer:
    image: apache/kafka:4.0.0
    depends_on:
      producer:
        condition: service_started
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G"
    command: ["/opt/kafka/bin/kafka-consumer-perf-test.sh",
              "--bootstrap-server", "broker:19092",
              "--topic", "test-topic",
              "--messages", "10000000000",
              "--reporting-interval", "5000",
              "--show-detailed-stats",
              "--timeout", "60000",
              "--fetch-size", "512000"]
