StylesPath = .vale/styles

MinAlertLevel = warning

Packages = Google, ai-tells

Vocab = Inkless

[formats]
java = md
scala = md
py = md

[*.{md,java,scala,py}]
BasedOnStyles = Google, ai-tells
# License headers
BlockIgnores = (?s)(Copyright \(C\).*?If not\, see), (?s)(Licensed to the Apache Software Foundation.*?limitations under the License\.)
