Configuration:
  Properties:
    Property:
      - name: "logPattern"
        value: "[%d] %p %m (%c)%n"

  # Appenders configuration
  # See: https://logging.apache.org/log4j/2.x/manual/appenders.html
  Appenders:
    Console:
      name: STDOUT
      PatternLayout:
        pattern: "${logPattern}"

  # Loggers configuration
  # See: https://logging.apache.org/log4j/2.x/manual/configuration.html#configuring-loggers
  Loggers:
    Root:
      level: ERROR
      AppenderRef:
        - ref: STDOUT
    Logger:
    - name: org.apache.kafka.server.log.remote.storage
      level: ERROR
    - name: io.aiven.inkless.control_plane.postgres.TSUnificationFetcher
      level: TRACE