services:
  broker: &base-broker
    image: aivenoy/kafka:4.1.0-inkless-SNAPSHOT
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "7070:7070" # prometheus metrics
      - "9999:9999" # jmx port
    environment: &base-broker-env
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_RACK: "az1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:19093,2@broker2:19093,101@broker101:19093,102@broker102:19093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
      KAFKA_LISTENERS: "CONTROLLER://:19093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      # Inkless

      ## Control Plane
      ### Postgresql
      KAFKA_INKLESS_CONTROL_PLANE_CLASS: "io.aiven.inkless.control_plane.postgres.PostgresControlPlane"
      KAFKA_INKLESS_CONTROL_PLANE_CONNECTION_STRING: "jdbc:postgresql://postgres:5432/inkless"
      KAFKA_INKLESS_CONTROL_PLANE_USERNAME: "admin"
      KAFKA_INKLESS_CONTROL_PLANE_PASSWORD: "admin"

      ## In-memory control plane
      # KAFKA_INKLESS_CONTROL_PLANE_CLASS: "io.aiven.inkless.control_plane.InMemoryControlPlane"

      ## Storage
      ### Minio
      KAFKA_INKLESS_STORAGE_BACKEND_CLASS: "io.aiven.inkless.storage_backend.s3.S3Storage"
      KAFKA_INKLESS_STORAGE_S3_PATH_STYLE_ACCESS_ENABLED: "true"
      KAFKA_INKLESS_STORAGE_S3_BUCKET_NAME: "inkless"
      KAFKA_INKLESS_STORAGE_S3_REGION: "us-east-1"
      KAFKA_INKLESS_STORAGE_S3_ENDPOINT_URL: "http://minio:9000"
      KAFKA_INKLESS_STORAGE_AWS_ACCESS_KEY_ID: "minioadmin"
      KAFKA_INKLESS_STORAGE_AWS_SECRET_ACCESS_KEY: "minioadmin"

      ### In-memory storage
      # KAFKA_INKLESS_STORAGE_BACKEND_CLASS: "io.aiven.inkless.storage_backend.in_memory.InMemoryStorage"

      # JMX
      KAFKA_JMX_PORT: 9999
      # Increase the heap size
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
      EXTRA_ARGS: -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=7070:/opt/prometheus-jmx-exporter/kafka.yml
    volumes:
      - ./../../../extra/prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
    depends_on:
      - postgres
      - minio

  broker2:
    <<: *base-broker
    ports:
      - "9093:9093"
      - "17070:7070" # prometheus metrics
      - "19999:9999" # jmx port
    environment:
      <<: *base-broker-env
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: "CONTROLLER://:19093,PLAINTEXT_HOST://:9093,PLAINTEXT://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9093,PLAINTEXT://broker2:19092"

  broker101:
    <<: *base-broker
    ports:
      - "9094:9094"
      - "17071:7070" # prometheus metrics
      - "18999:9999" # jmx port
    environment:
      <<: *base-broker-env
      KAFKA_NODE_ID: 101
      KAFKA_LISTENERS: "CONTROLLER://:19093,PLAINTEXT_HOST://:9094,PLAINTEXT://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9094,PLAINTEXT://broker101:19092"
      KAFKA_BROKER_RACK: "az2"

  broker102:
    <<: *base-broker
    ports:
      - "9095:9095"
      - "17072:7070" # prometheus metrics
      - "17999:9999" # jmx port
    environment:
      <<: *base-broker-env
      KAFKA_NODE_ID: 102
      KAFKA_LISTENERS: "CONTROLLER://:19093,PLAINTEXT_HOST://:9095,PLAINTEXT://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9095,PLAINTEXT://broker102:19092"
      KAFKA_BROKER_RACK: "az2"

  # Postgresql for control plane
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "inkless"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  # Object storage
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  minio-create_bucket:
    image: quay.io/minio/mc
    restart: "no"
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add local http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for Minio...';
        sleep 5;
      done;
      /usr/bin/mc mb local/inkless;
      exit 0;
      "

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./../../../extra/prometheus/config/:/etc/prometheus/
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./../../../extra/grafana/:/etc/grafana/provisioning/
